fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ArtesanIO\ArtesanusBundle\Entity\User
    group:
        group_class: ArtesanIO\ArtesanusBundle\Entity\Group

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig
