services:

    users.manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - ArtesanusBundle:Users
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager }

    groups.manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupsManager
        arguments:
            - ArtesanusBundle:Groups
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager }

    roles.manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - ArtesanusBundle:Roles
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager }

    users.manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - ArtesanusBundle:Users
        calls:
            - [setContainer, ['@service_container']]

    groups.manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupsManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Groups
        calls:
            - [setContainer, ['@service_container']]

    roles.manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Roles
        calls:
            - [setContainer, ['@service_container']]

    artesanus.files_manager:
        class: ArtesanIO\ArtesanusBundle\Model\FilesManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Files
        calls:
            - [setContainer, ['@service_container']]

    artesanus.categories_manager:
        class: ArtesanIO\ArtesanusBundle\Model\CategoriesManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Categories
        calls:
            - [setContainer, ['@service_container']]
