services:
    users.manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - ArtesanusBundle:Users
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    groups.manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupsManager
        arguments:
            - ArtesanusBundle:Groups
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    roles.manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - ArtesanusBundle:Roles
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    files.manager:
        class: ArtesanIO\ArtesanusBundle\Model\FilesManager
        arguments:
            - ArtesanusBundle:Files
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: Storage}

    categories.manager:
        class: ArtesanIO\ArtesanusBundle\Model\CategoriesManager
        arguments:
            - ArtesanusBundle:Categories
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, in_console: true }
