services:
    users.manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - ArtesanusBundle:Users
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }
