services:

    artesanus.user_manager:
        class: ArtesanIO\ArtesanusBundle\Model\UserManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\User
            - @artesanio.encoder

    artesanus.group_manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Group

    artesanus.roles_manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - @artesanus.roles
        calls:
            - [setContainer, ['@service_container']]

    artesanus.files_manager:
        class: ArtesanIO\ArtesanusBundle\Model\FilesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Files
        calls:
            - [setContainer, ['@service_container']]

    artesanus.categories_manager:
        class: ArtesanIO\ArtesanusBundle\Model\CategoriesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Categories
        calls:
            - [setContainer, ['@service_container']]
