services:
    users.manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Users
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    groups.manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupsManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Groups
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    roles.manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Roles
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager, package: ACL }

    categories.manager:
        class: ArtesanIO\ArtesanusBundle\Model\CategoriesManager
        arguments:
            - ArtesanIO\ArtesanusBundle\Entity\Categories
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: artesanus.manager }
