services:

    artesanus.users_manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsersManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Users
        calls:
            - [setContainer, ['@service_container']]

    artesanus.group_manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Group
        calls:
            - [setContainer, ['@service_container']]

    artesanus.roles_manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Roles
        calls:
            - [setContainer, ['@service_container']]

    artesanus.files_manager:
        class: ArtesanIO\ArtesanusBundle\Model\FilesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Files
        calls:
            - [setContainer, ['@service_container']]

    artesanus.categories_manager:
        class: ArtesanIO\ArtesanusBundle\Model\CategoriesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Categories
        calls:
            - [setContainer, ['@service_container']]
