artesanus_admin:
    resource: "@ArtesanusBundle/Resources/config/routing/all.yml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

home:
    path:     /home
    defaults: { _controller: ArtesanusBundle:Home:home }
