artesanus:
    resource: "@ArtesanusBundle/Resources/config/routing/all.yml"
    prefix: /artesanus

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

artesanus_front_user_profile:
    path:     /user-profile
    defaults: { _controller: ArtesanusBundle:Profile:profile, type: user-profile }
    requirements:
        type: user-profile
