services:
    artesanus.managers:
        class: ArtesanIO\ArtesanusBundle\Utils\ArtesanusManagers
        calls:
            - [setContainer, ['@service_container']]

    artesanus.routes_managers:
        class: ArtesanIO\ArtesanusBundle\Routing\RoutesManagers
        arguments:
            - @artesanus.managers
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, ['@service_container']]

    artesanus.nav_menu.listener:
        class: ArtesanIO\ArtesanusBundle\EventListener\ArtesanusMenuListener
        arguments:
            - @artesanus.managers
        tags:
          - { name: kernel.event_listener, event: artesanus.navbar, method: onArtesanusNavBar }

    artesanus.entity_prefix:
        class: ArtesanIO\ArtesanusBundle\Utils\EntityPrefix
