services:

    artesanus.managers:
        class: ArtesanIO\ArtesanusBundle\Utils\ArtesanusManagers
        calls:
            - [setContainer, ['@service_container']]

    artesanus.routes_managers:
        class: ArtesanIO\ArtesanusBundle\Routing\RoutesManagers
        arguments:
            - @artesanus.managers
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, ['@service_container']]

    artesanus.users_provider:
        class: ArtesanIO\ArtesanusBundle\Utils\UsersProvider
        arguments:
            - @artesanus.users_manager

    artesanus.encoder:
        class:  ArtesanIO\ArtesanusBundle\Utils\Encoder
        arguments:
            - @security.encoder_factory

    artesanus.sluger_role:
        class:  ArtesanIO\ArtesanusBundle\Utils\SlugerRole

    artesanio.profile.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: artesanio_user_profile }

    artesanio.group.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\GroupFormType
        tags:
            - { name: form.type, alias: artesanio_user_group }

    artesanus.group_subscriber:
        class: ArtesanIO\ArtesanusBundle\Form\EventListener\GroupSubscriber

    artesanus.nav_menu.listener:
        class: ArtesanIO\ArtesanusBundle\EventListener\ArtesanusMenuListener
        tags:
          - { name: kernel.event_listener, event: artesanus.navbar, method: onArtesanusNavBar }

    artesanus.roles.listener:
        class: ArtesanIO\ArtesanusBundle\EventListener\ArtesanusRolesListener
        tags:
            - { name: kernel.event_listener, event: artesanus.roles.event, method: roles }

    artesanus.roles:
        class: ArtesanIO\ArtesanusBundle\Model\Roles

    artesanus.loggin_success_handler:
        class: ArtesanIO\ArtesanusBundle\Utils\LoginSuccessHandler
        arguments:
            - @artesanus.roles_manager
            - @router
            - @security.context

    artesanus.logout_success_handler:
        class: ArtesanIO\ArtesanusBundle\Utils\LogoutSuccessHandler
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    artesanus.flashers:
        class: ArtesanIO\ArtesanusBundle\Utils\Flashers
        arguments:
            - @session

    artesanus.flashers_extension:
        class: ArtesanIO\ArtesanusBundle\Utils\FlashersExtension
        tags:
            - { name: twig.extension }

    artesanus.cartero:
        class:  ArtesanIO\ArtesanusBundle\Utils\Cartero
        arguments:
            - @mailer
            - @service_container

    artesanus.slugger:
        class: ArtesanIO\ArtesanusBundle\Utils\Slugger

    artesanus.data_fixtures:
        class: ArtesanIO\ArtesanusBundle\DataFixtures\ORM\ArtesanusLoader
        calls:
            - [setUsersManager, ['@artesanus.users_manager']]
