services:
    artesanus.managers:
        class: ArtesanIO\ArtesanusBundle\Utils\ArtesanusManagers
        calls:
            - [setContainer, ['@service_container']]

    artesanus.routes_managers:
        class: ArtesanIO\ArtesanusBundle\Routing\RoutesManagers
        arguments:
            - @artesanus.managers
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, ['@service_container']]
