services:
    users_type:
        class: ArtesanIO\ArtesanusBundle\Form\UsersType
        tags:
            - { name: form.type, alias: users_type }

    artesanus.users_password_type:
        class: ArtesanIO\ArtesanusBundle\Form\UsersPasswordType
        tags:
            - { name: form.type, alias: artesanus_users_password_type }

    artesanus.groups_type:
        class: ArtesanIO\ArtesanusBundle\Form\GroupsType
        tags:
            - { name: form.type, alias: artesanus_groups_type }

    artesanus.groups_roles_type:
        class: ArtesanIO\ArtesanusBundle\Form\GroupsRolesType
        tags:
            - { name: form.type, alias: artesanus_groups_roles_type }

    artesanio.grupo_roles_type:
        class: ArtesanIO\ArtesanusBundle\Form\GrupoRolesType
        tags:
            - { name: form.type, alias: artesanio_acl_grupo_roles }

    artesanus.roles_type:
        class: ArtesanIO\ArtesanusBundle\Form\RolesType
        tags:
            - { name: form.type, alias: artesanus_acl_roles }

    artesanus.user_type:
        class: ArtesanIO\ArtesanusBundle\Form\UserType
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: artesanus_user_type }

    artesanus.profile_type:
        class: ArtesanIO\ArtesanusBundle\Form\ProfileType
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: artesanus_profile_type }

    artesanus.files_type:
        class: ArtesanIO\ArtesanusBundle\Form\FilesType
        tags:
            - { name: form.type, alias: artesanus_files_type }

    artesanus.categories_type:
        class: ArtesanIO\ArtesanusBundle\Form\CategoriesType
        tags:
            - { name: form.type, alias: artesanus_categories_type }
