services:
    users.type:
        class: ArtesanIO\ArtesanusBundle\Form\UsersType
        tags:
            - { name: form.type, alias: users_type }

    users_password_type:
        class: ArtesanIO\ArtesanusBundle\Form\UsersPasswordType
        tags:
            - { name: form.type, alias: users_password_type }

    groups.type:
        class: ArtesanIO\ArtesanusBundle\Form\GroupsType
        tags:
            - { name: form.type, alias: groups_type }

    groups_roles.type:
        class: ArtesanIO\ArtesanusBundle\Form\GroupsRolesType
        tags:
            - { name: form.type, alias: groups_roles_type }

    roles.type:
        class: ArtesanIO\ArtesanusBundle\Form\RolesType
        tags:
            - { name: form.type, alias: roles_type }

    files.type:
        class: ArtesanIO\ArtesanusBundle\Form\FilesType
        tags:
            - { name: form.type, alias: files_type }

    categories.type:
        class: ArtesanIO\ArtesanusBundle\Form\CategoriesType
        tags:
            - { name: form.type, alias: categories_type }
