<?php

namespace ArtesanIO\ArtesanusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRolesRepository extends EntityRepository
{
}
