<?php

namespace ArtesanIO\ArtesanusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{

    public function findUsernameOrEmail($user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT u FROM ArtesanusBundle:Users u
                 WHERE u.username = :user
                 OR u.email = :user
                '
            )
            ->setParameter('user', $user)
            ->getSingleResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
