artesanus_console_acl_users:
    path:     /users
    defaults: { _controller: ArtesanusBundle:User:users }

artesanus_console_acl_users_new:
    path:     /users/new
    defaults: { _controller: ArtesanusBundle:User:new }

artesanus_console_acl_users_delete:
    path:     /user-delete/{id}
    defaults: { _controller: ArtesanusBundle:User:delete }

artesanus_console_acl_user:
    path:     /user/{id}
    defaults: { _controller: ArtesanusBundle:User:user }

artesanus_console_acl_groups:
    path:     /groups
    defaults: { _controller: ArtesanusBundle:Group:groups }

grupos:
    path:     /grupos
    defaults: { _controller: ArtesanusBundle:Group:grupos }

artesanus_console_acl_groups_new:
    path:     /groups/new
    defaults: { _controller: ArtesanusBundle:Group:new }

artesanus_console_acl_group:
    path:     /group/{id}
    defaults: { _controller: ArtesanusBundle:Group:group }

artesanus_console_acl_roles:
    path:     /roles
    defaults: { _controller: ArtesanusBundle:Roles:roles }

artesanus_console_acl_roles_new:
    path:     /roles/new
    defaults: { _controller: ArtesanusBundle:Roles:new }

artesanus_console_acl_roles_delete:
    path:     /roles/delete
    defaults: { _controller: ArtesanusBundle:Roles:delete }

artesanus_console_acl_role:
    path:     /role/{id}
    defaults: { _controller: ArtesanusBundle:Roles:role }

artesanus_console_acl_role:
    path:     /role/{id}
    defaults: { _controller: ArtesanusBundle:Roles:role }
