artesanus_console:
    resource: "@ArtesanusBundle/Resources/config/routing/console.yml"
    prefix: /console

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /

fos_user_resetting_request:
    path:     /forgot
    defaults: { _controller: FOSUserBundle:Resetting:request }
