artesanus_console:
    resource: "@ArtesanusBundle/Resources/config/routing/console.yml"
    prefix: /console

artesanus_login:
    path:     /login
    defaults: { _controller: ArtesanusBundle:Login:login }

login_check:
    pattern:   /login_check

artesanus_logout:
    path:   /logout

artesanus_register:
    path:     /register
    defaults: { _controller: ArtesanusBundle:User:register }
