artesanus_console:
    resource: "@ArtesanusBundle/Resources/config/routing/console.yml"
    prefix: /console

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

artesanus_front_user_profile:
    path:     /profile
    defaults: { _controller: ArtesanusBundle:Profile:profile }
    requirements:
