artesanus_console:
    resource: "@ArtesanusBundle/Resources/config/routing/console.yml"
    prefix: /console

artesanus_security_login:
    path:     /login
    defaults: { _controller: ArtesanusBundle:Security:login }

artesanus_security_login_check:
    pattern:   /login_check

artesanus_security_logout:
    path:   /logout

artesanus_security_register:
    path:     /register
    defaults: { _controller: ArtesanusBundle:User:register }
